### ISSUE TITLE
While running graphictest it got a "Soft WDT" reset

### ISSUE THREAD

**Issue by stanleyseow** [InsanityMoose/ILI9341_ESP8266#1]
�!�L�<1���ILI9341 Test!
Display Power Mode: 0xFF
MADCTL Mode: 0xFF
Pixel Format: 0xFF
Image Format: 0xFF
Self Diagnostic: 0xFF
Benchmark                Time (microseconds)
Screen fill              2160584
Text                     155157
Lines  
Soft WDT reset

ctx: cont 
sp: 3ffefe50 end: 3fff00f0 offset: 01b0

> > > stack>>>
> > > 3fff0000:  000000e9 000000b5 3ffeef68 40202891  
> > > 3fff0010:  000000e9 000000b5 3ffeef68 40202e50  
> > > 3fff0020:  00000000 00000001 3ffeef68 40202891  
> > > 3fff0030:  00000000 000000f0 3ffeef68 000000ef  
> > > 3fff0040:  000000e9 000000ef 00000028 402043fd  
> > > 3fff0050:  00000000 00000001 000007ff 000000ba  
> > > 3fff0060:  3ffeef68 000000b5 3ffe8b31 3ffef0bc  
> > > 3fff0070:  000000f0 000007ff 3ffeef68 000000ba  
> > > 3fff0080:  000000f0 000007ff 3ffeef68 40201ade  
> > > 3fff0090:  0000013f 000000ef 00000140 3ffeefd0  
> > > 3fff00a0:  000000ef 3ffef0bc 4020418c 3ffef0d0  
> > > 3fff00b0:  3ffef090 00000018 4022d201 3ffef0bc  
> > > 3fff00c0:  000000ff 000000ff 3ffef090 40202384  
> > > 3fff00d0:  3fffdc20 00000000 3ffef0b4 402041ca  
> > > 3fff00e0:  00000000 00000000 3ffef0d0 40100114  
> > > <<<stack<<<

**Comment by InsanityMoose** [comment]
I suspect there needs to be a few yield() in between the tests to prevent the watchdog triggering.

**Comment by stanleyseow** [comment]
Thanks... yield() solved it... closing the case...
